

image: node:6.5.0
pages:
  stage: deploy
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - build # mandatory, other folder won't work
  only:
  - master # or dev, the branch you want to publish